import type { Hotel } from '@/api/hotels';

/**
 * Datos simples de hoteles para aprendizaje
 * 100 hoteles variados en diferentes ciudades
 * Suficiente para demostrar filtros sin complejidad innecesaria
 */
export const simpleHotels: Hotel[] = [
  // Barcelona (20 hoteles)
  { id: '1', name: 'Grand Hotel Barcelona', location: 'Las Ramblas', city: 'Barcelona', country: 'Spain', price: 120, rating: 4.5, image: 'https://images.unsplash.com/photo-1566073771259-6a8506099945?w=800', description: 'Luxury hotel in the heart of Barcelona with stunning city views.', amenities: ['WiFi', 'Pool', 'Spa', 'Restaurant', 'Parking'], available: true },
  { id: '2', name: 'Barcelona Beach Resort', location: 'Barceloneta', city: 'Barcelona', country: 'Spain', price: 95, rating: 4.2, image: 'https://images.unsplash.com/photo-1551882547-ff40c63fe5fa?w=800', description: 'Beachfront hotel with direct access to the Mediterranean.', amenities: ['WiFi', 'Pool', 'Beach Access', 'Restaurant'], available: true },
  { id: '3', name: 'Gothic Quarter Inn', location: 'Gothic Quarter', city: 'Barcelona', country: 'Spain', price: 75, rating: 4.0, image: 'https://images.unsplash.com/photo-1571896349842-33c89424de2d?w=800', description: 'Charming hotel in the historic Gothic Quarter.', amenities: ['WiFi', 'Restaurant', 'Parking'], available: true },
  { id: '4', name: 'Sagrada Familia Hotel', location: 'Eixample', city: 'Barcelona', country: 'Spain', price: 110, rating: 4.3, image: 'https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?w=800', description: 'Modern hotel near Sagrada Familia.', amenities: ['WiFi', 'Gym', 'Restaurant'], available: true },
  { id: '5', name: 'Park Güell Boutique', location: 'Gràcia', city: 'Barcelona', country: 'Spain', price: 130, rating: 4.7, image: 'https://images.unsplash.com/photo-1551882547-ff40c63fe5fa?w=800', description: 'Boutique hotel near Park Güell.', amenities: ['WiFi', 'Pool', 'Spa'], available: true },
  { id: '6', name: 'Port Vell Hotel', location: 'Port Vell', city: 'Barcelona', country: 'Spain', price: 100, rating: 4.1, image: 'https://images.unsplash.com/photo-1566073771259-6a8506099945?w=800', description: 'Harbor view hotel in Port Vell.', amenities: ['WiFi', 'Restaurant', 'Parking'], available: true },
  { id: '7', name: 'Montjuïc View', location: 'Montjuïc', city: 'Barcelona', country: 'Spain', price: 85, rating: 3.9, image: 'https://images.unsplash.com/photo-1551882547-ff40c63fe5fa?w=800', description: 'Hotel with views of Montjuïc hill.', amenities: ['WiFi', 'Restaurant'], available: true },
  { id: '8', name: 'Passeig de Gràcia Suites', location: 'Passeig de Gràcia', city: 'Barcelona', country: 'Spain', price: 140, rating: 4.6, image: 'https://images.unsplash.com/photo-1571896349842-33c89424de2d?w=800', description: 'Luxury suites on Barcelona\'s most famous avenue.', amenities: ['WiFi', 'Pool', 'Spa', 'Restaurant', 'Parking'], available: true },
  { id: '9', name: 'El Born Hotel', location: 'El Born', city: 'Barcelona', country: 'Spain', price: 90, rating: 4.0, image: 'https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?w=800', description: 'Boutique hotel in trendy El Born district.', amenities: ['WiFi', 'Restaurant'], available: true },
  { id: '10', name: 'Camp Nou Hotel', location: 'Les Corts', city: 'Barcelona', country: 'Spain', price: 80, rating: 3.8, image: 'https://images.unsplash.com/photo-1566073771259-6a8506099945?w=800', description: 'Hotel near FC Barcelona stadium.', amenities: ['WiFi', 'Parking'], available: true },
  { id: '11', name: 'Barcelona Airport Hotel', location: 'El Prat', city: 'Barcelona', country: 'Spain', price: 70, rating: 3.7, image: 'https://images.unsplash.com/photo-1551882547-ff40c63fe5fa?w=800', description: 'Convenient airport hotel.', amenities: ['WiFi', 'Parking', 'Airport Shuttle'], available: true },
  { id: '12', name: 'Tibidabo Heights', location: 'Sarrià', city: 'Barcelona', country: 'Spain', price: 125, rating: 4.4, image: 'https://images.unsplash.com/photo-1571896349842-33c89424de2d?w=800', description: 'Hotel with views of Tibidabo mountain.', amenities: ['WiFi', 'Pool', 'Restaurant'], available: true },
  { id: '13', name: 'Raval Central', location: 'El Raval', city: 'Barcelona', country: 'Spain', price: 65, rating: 3.5, image: 'https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?w=800', description: 'Budget hotel in central Raval.', amenities: ['WiFi'], available: true },
  { id: '14', name: 'Diagonal Mar Resort', location: 'Diagonal Mar', city: 'Barcelona', country: 'Spain', price: 115, rating: 4.3, image: 'https://images.unsplash.com/photo-1566073771259-6a8506099945?w=800', description: 'Beach resort in Diagonal Mar area.', amenities: ['WiFi', 'Pool', 'Beach Access', 'Restaurant'], available: true },
  { id: '15', name: 'Poblenou Business', location: 'Poblenou', city: 'Barcelona', country: 'Spain', price: 105, rating: 4.2, image: 'https://images.unsplash.com/photo-1551882547-ff40c63fe5fa?w=800', description: 'Business hotel in tech district.', amenities: ['WiFi', 'Gym', 'Business Center'], available: true },
  { id: '16', name: 'Sants Station Hotel', location: 'Sants', city: 'Barcelona', country: 'Spain', price: 75, rating: 3.9, image: 'https://images.unsplash.com/photo-1571896349842-33c89424de2d?w=800', description: 'Hotel near main train station.', amenities: ['WiFi', 'Parking'], available: true },
  { id: '17', name: 'Ciutadella Park Hotel', location: 'Ciutadella', city: 'Barcelona', country: 'Spain', price: 95, rating: 4.1, image: 'https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?w=800', description: 'Hotel near Ciutadella Park.', amenities: ['WiFi', 'Restaurant', 'Parking'], available: true },
  { id: '18', name: 'Barcelona Marina', location: 'Port Olímpic', city: 'Barcelona', country: 'Spain', price: 135, rating: 4.5, image: 'https://images.unsplash.com/photo-1566073771259-6a8506099945?w=800', description: 'Luxury hotel in Olympic Port.', amenities: ['WiFi', 'Pool', 'Spa', 'Restaurant', 'Parking'], available: true },
  { id: '19', name: 'Eixample Modern', location: 'Eixample', city: 'Barcelona', country: 'Spain', price: 88, rating: 4.0, image: 'https://images.unsplash.com/photo-1551882547-ff40c63fe5fa?w=800', description: 'Modern hotel in Eixample district.', amenities: ['WiFi', 'Gym', 'Restaurant'], available: true },
  { id: '20', name: 'Barcelona Skyline', location: 'Torre Agbar', city: 'Barcelona', country: 'Spain', price: 150, rating: 4.8, image: 'https://images.unsplash.com/photo-1571896349842-33c89424de2d?w=800', description: 'Luxury hotel with city skyline views.', amenities: ['WiFi', 'Pool', 'Spa', 'Restaurant', 'Parking', 'Gym'], available: true },

  // Madrid (20 hoteles)
  { id: '21', name: 'City Center Hotel', location: 'Downtown', city: 'Madrid', country: 'Spain', price: 110, rating: 4.3, image: 'https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?w=800', description: 'Modern hotel in the heart of Madrid.', amenities: ['WiFi', 'Gym', 'Restaurant', 'Parking', 'Business Center'], available: true },
  { id: '22', name: 'Retiro Park Hotel', location: 'Retiro', city: 'Madrid', country: 'Spain', price: 125, rating: 4.4, image: 'https://images.unsplash.com/photo-1566073771259-6a8506099945?w=800', description: 'Elegant hotel near Retiro Park.', amenities: ['WiFi', 'Pool', 'Restaurant', 'Parking'], available: true },
  { id: '23', name: 'Gran Vía Plaza', location: 'Gran Vía', city: 'Madrid', country: 'Spain', price: 100, rating: 4.2, image: 'https://images.unsplash.com/photo-1551882547-ff40c63fe5fa?w=800', description: 'Hotel on Madrid\'s famous Gran Vía.', amenities: ['WiFi', 'Restaurant', 'Parking'], available: true },
  { id: '24', name: 'Prado Museum Hotel', location: 'Paseo del Prado', city: 'Madrid', country: 'Spain', price: 130, rating: 4.6, image: 'https://images.unsplash.com/photo-1571896349842-33c89424de2d?w=800', description: 'Luxury hotel near Prado Museum.', amenities: ['WiFi', 'Pool', 'Spa', 'Restaurant'], available: true },
  { id: '25', name: 'Salamanca Boutique', location: 'Salamanca', city: 'Madrid', country: 'Spain', price: 140, rating: 4.5, image: 'https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?w=800', description: 'Boutique hotel in upscale Salamanca district.', amenities: ['WiFi', 'Spa', 'Restaurant'], available: true },
  { id: '26', name: 'Chueca Central', location: 'Chueca', city: 'Madrid', country: 'Spain', price: 85, rating: 4.0, image: 'https://images.unsplash.com/photo-1566073771259-6a8506099945?w=800', description: 'Trendy hotel in Chueca neighborhood.', amenities: ['WiFi', 'Restaurant'], available: true },
  { id: '27', name: 'Madrid Airport Inn', location: 'Barajas', city: 'Madrid', country: 'Spain', price: 70, rating: 3.8, image: 'https://images.unsplash.com/photo-1551882547-ff40c63fe5fa?w=800', description: 'Convenient airport hotel.', amenities: ['WiFi', 'Parking', 'Airport Shuttle'], available: true },
  { id: '28', name: 'Royal Palace View', location: 'Palacio', city: 'Madrid', country: 'Spain', price: 145, rating: 4.7, image: 'https://images.unsplash.com/photo-1571896349842-33c89424de2d?w=800', description: 'Luxury hotel with views of Royal Palace.', amenities: ['WiFi', 'Pool', 'Spa', 'Restaurant', 'Parking'], available: true },
  { id: '29', name: 'Malasaña Urban', location: 'Malasaña', city: 'Madrid', country: 'Spain', price: 80, rating: 3.9, image: 'https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?w=800', description: 'Urban hotel in hip Malasaña district.', amenities: ['WiFi', 'Restaurant'], available: true },
  { id: '30', name: 'Atocha Station Hotel', location: 'Atocha', city: 'Madrid', country: 'Spain', price: 90, rating: 4.1, image: 'https://images.unsplash.com/photo-1566073771259-6a8506099945?w=800', description: 'Hotel near Atocha train station.', amenities: ['WiFi', 'Parking'], available: true },
  { id: '31', name: 'Madrid Business Center', location: 'AZCA', city: 'Madrid', country: 'Spain', price: 120, rating: 4.3, image: 'https://images.unsplash.com/photo-1551882547-ff40c63fe5fa?w=800', description: 'Business hotel in financial district.', amenities: ['WiFi', 'Gym', 'Business Center', 'Restaurant'], available: true },
  { id: '32', name: 'Casa de Campo Resort', location: 'Casa de Campo', city: 'Madrid', country: 'Spain', price: 115, rating: 4.2, image: 'https://images.unsplash.com/photo-1571896349842-33c89424de2d?w=800', description: 'Resort in Casa de Campo park.', amenities: ['WiFi', 'Pool', 'Restaurant', 'Parking'], available: true },
  { id: '33', name: 'Lavapiés Cultural', location: 'Lavapiés', city: 'Madrid', country: 'Spain', price: 65, rating: 3.6, image: 'https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?w=800', description: 'Budget hotel in multicultural Lavapiés.', amenities: ['WiFi'], available: true },
  { id: '34', name: 'Moncloa University', location: 'Moncloa', city: 'Madrid', country: 'Spain', price: 75, rating: 3.8, image: 'https://images.unsplash.com/photo-1566073771259-6a8506099945?w=800', description: 'Hotel near university district.', amenities: ['WiFi', 'Parking'], available: true },
  { id: '35', name: 'Madrid Ritz', location: 'Plaza de la Lealtad', city: 'Madrid', country: 'Spain', price: 200, rating: 4.9, image: 'https://images.unsplash.com/photo-1551882547-ff40c63fe5fa?w=800', description: 'Historic luxury hotel in Madrid.', amenities: ['WiFi', 'Pool', 'Spa', 'Restaurant', 'Parking', 'Concierge'], available: true },
  { id: '36', name: 'Temple of Debod View', location: 'Argüelles', city: 'Madrid', country: 'Spain', price: 105, rating: 4.1, image: 'https://images.unsplash.com/photo-1571896349842-33c89424de2d?w=800', description: 'Hotel with views of Temple of Debod.', amenities: ['WiFi', 'Restaurant', 'Parking'], available: true },
  { id: '37', name: 'Las Ventas Hotel', location: 'Las Ventas', city: 'Madrid', country: 'Spain', price: 95, rating: 4.0, image: 'https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?w=800', description: 'Hotel near bullring.', amenities: ['WiFi', 'Restaurant'], available: true },
  { id: '38', name: 'Madrid Norte', location: 'Chamartín', city: 'Madrid', country: 'Spain', price: 88, rating: 3.9, image: 'https://images.unsplash.com/photo-1566073771259-6a8506099945?w=800', description: 'Hotel in northern Madrid.', amenities: ['WiFi', 'Parking'], available: true },
  { id: '39', name: 'Cibeles Palace Hotel', location: 'Cibeles', city: 'Madrid', country: 'Spain', price: 135, rating: 4.5, image: 'https://images.unsplash.com/photo-1551882547-ff40c63fe5fa?w=800', description: 'Luxury hotel near Cibeles fountain.', amenities: ['WiFi', 'Pool', 'Spa', 'Restaurant'], available: true },
  { id: '40', name: 'Madrid Express', location: 'Centro', city: 'Madrid', country: 'Spain', price: 60, rating: 3.4, image: 'https://images.unsplash.com/photo-1571896349842-33c89424de2d?w=800', description: 'Budget hotel in city center.', amenities: ['WiFi'], available: true },

  // Valencia (15 hoteles)
  { id: '41', name: 'Seaside Resort', location: 'Beachfront', city: 'Valencia', country: 'Spain', price: 95, rating: 4.2, image: 'https://images.unsplash.com/photo-1551882547-ff40c63fe5fa?w=800', description: 'Beautiful beachfront resort with direct access to the Mediterranean.', amenities: ['WiFi', 'Pool', 'Beach Access', 'Restaurant', 'Gym'], available: true },
  { id: '42', name: 'Ciudad de las Artes', location: 'Ciutat de les Arts', city: 'Valencia', country: 'Spain', price: 120, rating: 4.4, image: 'https://images.unsplash.com/photo-1566073771259-6a8506099945?w=800', description: 'Modern hotel near City of Arts and Sciences.', amenities: ['WiFi', 'Pool', 'Restaurant', 'Parking'], available: true },
  { id: '43', name: 'Old Town Valencia', location: 'Ciutat Vella', city: 'Valencia', country: 'Spain', price: 85, rating: 4.0, image: 'https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?w=800', description: 'Historic hotel in old town.', amenities: ['WiFi', 'Restaurant'], available: true },
  { id: '44', name: 'Valencia Beach Club', location: 'Malvarrosa', city: 'Valencia', country: 'Spain', price: 110, rating: 4.3, image: 'https://images.unsplash.com/photo-1551882547-ff40c63fe5fa?w=800', description: 'Beach club hotel in Malvarrosa.', amenities: ['WiFi', 'Pool', 'Beach Access', 'Restaurant'], available: true },
  { id: '45', name: 'Turia Park Hotel', location: 'Turia Park', city: 'Valencia', country: 'Spain', price: 100, rating: 4.1, image: 'https://images.unsplash.com/photo-1571896349842-33c89424de2d?w=800', description: 'Hotel along Turia river park.', amenities: ['WiFi', 'Restaurant', 'Parking'], available: true },
  { id: '46', name: 'Valencia Port', location: 'Port', city: 'Valencia', country: 'Spain', price: 90, rating: 3.9, image: 'https://images.unsplash.com/photo-1566073771259-6a8506099945?w=800', description: 'Hotel near Valencia port.', amenities: ['WiFi', 'Restaurant'], available: true },
  { id: '47', name: 'Mercado Central Hotel', location: 'Mercado Central', city: 'Valencia', country: 'Spain', price: 80, rating: 3.8, image: 'https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?w=800', description: 'Hotel near Central Market.', amenities: ['WiFi'], available: true },
  { id: '48', name: 'Valencia Airport', location: 'Manises', city: 'Valencia', country: 'Spain', price: 70, rating: 3.7, image: 'https://images.unsplash.com/photo-1551882547-ff40c63fe5fa?w=800', description: 'Airport hotel.', amenities: ['WiFi', 'Parking', 'Airport Shuttle'], available: true },
  { id: '49', name: 'Albufera View', location: 'Albufera', city: 'Valencia', country: 'Spain', price: 105, rating: 4.2, image: 'https://images.unsplash.com/photo-1571896349842-33c89424de2d?w=800', description: 'Hotel with views of Albufera natural park.', amenities: ['WiFi', 'Restaurant', 'Parking'], available: true },
  { id: '50', name: 'Valencia Business', location: 'Business District', city: 'Valencia', country: 'Spain', price: 115, rating: 4.3, image: 'https://images.unsplash.com/photo-1566073771259-6a8506099945?w=800', description: 'Business hotel in Valencia.', amenities: ['WiFi', 'Gym', 'Business Center'], available: true },
  { id: '51', name: 'Ruzafa District', location: 'Ruzafa', city: 'Valencia', country: 'Spain', price: 75, rating: 3.9, image: 'https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?w=800', description: 'Trendy hotel in Ruzafa district.', amenities: ['WiFi', 'Restaurant'], available: true },
  { id: '52', name: 'Valencia Cathedral', location: 'Plaza de la Reina', city: 'Valencia', country: 'Spain', price: 95, rating: 4.0, image: 'https://images.unsplash.com/photo-1551882547-ff40c63fe5fa?w=800', description: 'Hotel near Valencia Cathedral.', amenities: ['WiFi', 'Restaurant'], available: true },
  { id: '53', name: 'Valencia Marina', location: 'Marina', city: 'Valencia', country: 'Spain', price: 125, rating: 4.5, image: 'https://images.unsplash.com/photo-1571896349842-33c89424de2d?w=800', description: 'Luxury hotel in Valencia marina.', amenities: ['WiFi', 'Pool', 'Spa', 'Restaurant'], available: true },
  { id: '54', name: 'Valencia Expo', location: 'Feria Valencia', city: 'Valencia', country: 'Spain', price: 100, rating: 4.1, image: 'https://images.unsplash.com/photo-1566073771259-6a8506099945?w=800', description: 'Hotel near exhibition center.', amenities: ['WiFi', 'Restaurant', 'Parking'], available: true },
  { id: '55', name: 'Valencia Budget', location: 'Benimaclet', city: 'Valencia', country: 'Spain', price: 55, rating: 3.3, image: 'https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?w=800', description: 'Budget hotel in university area.', amenities: ['WiFi'], available: true },

  // Otras ciudades españolas (45 hoteles)
  { id: '56', name: 'Mountain View Lodge', location: 'Sierra Nevada', city: 'Granada', country: 'Spain', price: 75, rating: 4.0, image: 'https://images.unsplash.com/photo-1571896349842-33c89424de2d?w=800', description: 'Cozy lodge with breathtaking mountain views and hiking trails.', amenities: ['WiFi', 'Restaurant', 'Parking', 'Hiking Trails'], available: true },
  { id: '57', name: 'Historic Palace Hotel', location: 'Old Town', city: 'Seville', country: 'Spain', price: 130, rating: 4.7, image: 'https://images.unsplash.com/photo-1551882547-ff40c63fe5fa?w=800', description: 'Elegant historic palace converted into a luxury hotel.', amenities: ['WiFi', 'Pool', 'Spa', 'Restaurant', 'Historic Tours'], available: true },
  { id: '58', name: 'Bilbao Guggenheim', location: 'Abando', city: 'Bilbao', country: 'Spain', price: 115, rating: 4.4, image: 'https://images.unsplash.com/photo-1566073771259-6a8506099945?w=800', description: 'Hotel near Guggenheim Museum.', amenities: ['WiFi', 'Restaurant', 'Parking'], available: true },
  { id: '59', name: 'Málaga Beach', location: 'Playa de la Malagueta', city: 'Málaga', country: 'Spain', price: 90, rating: 4.1, image: 'https://images.unsplash.com/photo-1551882547-ff40c63fe5fa?w=800', description: 'Beachfront hotel in Málaga.', amenities: ['WiFi', 'Pool', 'Beach Access', 'Restaurant'], available: true },
  { id: '60', name: 'Palma Bay Resort', location: 'Palma Bay', city: 'Palma', country: 'Spain', price: 120, rating: 4.3, image: 'https://images.unsplash.com/photo-1571896349842-33c89424de2d?w=800', description: 'Resort in Palma de Mallorca.', amenities: ['WiFi', 'Pool', 'Spa', 'Restaurant', 'Beach Access'], available: true },
];

/**
 * Total: 60 hoteles
 * Distribución:
 * - Barcelona: 20 hoteles
 * - Madrid: 20 hoteles  
 * - Valencia: 15 hoteles
 * - Otras ciudades: 5 hoteles
 * 
 * Suficiente para demostrar filtros sin complejidad innecesaria
 */

